### ISSUE TITLE
推荐将GitHub源换成https://github.91chi.fun/https://github.com

### ISSUE THREAD

**Issue by shy113** [UtermuxBlog/termux-metasploit#1]
https://github.91chi.fun/https://github.com
这个源更快一点,不过只对.git结尾有效
以下地方需进行处理
第42行 LICENSE=$(curl -L ${mirror}/UtermuxBlog/termux-metasploit/raw/main/LICENSE) > /dev/null 2>&1
LICENSE=$(curl -L https://github.com/UtermuxBlog/termux-metasploit/raw/main/LICENSE) > /dev/null 2>&1

**Comment by shy113** [comment]
这个脚本执行的前提是在用户安装ruby的基础上,希望作者提醒用户安装ruby...我装不上的原因就是,没装ruby

**Comment by 2096779623** [comment]
> 这个脚本执行的前提是在用户安装ruby的基础上,希望作者提醒用户安装ruby...我装不上的原因就是,没装ruby

https://github.com/UtermuxBlog/termux-metasploit/blob/main/installer.sh#L53
